server:
  port: 8081
spring:
  application:
    name: finance_service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/finance_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Jakarta
  jpa:
    # Validasi schema tanpa mengubahnya otomatis (kita pakai Flyway untuk itu)
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Memudahkan debug query di log
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATE_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATE_MS}