server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${USER_DB_NAME:user_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    # Validasi schema tanpa mengubahnya otomatis (kita pakai Flyway untuk itu)
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Memudahkan debug query di log
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATE_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATE_MS}