services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_mylife
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5000:5432 # artinya di laptop pakai 5000, di container sebagai 5432
    volumes:
      - mylife-postgresql:/var/lib/postgresql/data
volumes:
  mylife-postgresql:
    external: true
# for testing only bruh..